name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET: "lut-it-flask-application-packges"
  EB_APPLICATION_NAME : "MyFlask"
  EB_ENVIRMENT_NAME.  : "MyFlack-env"
  DEPLOY_PACKAGE_NAME : "Flask-app-${{github.sha}}.zip"
  AWS_REGION_NAME.    : "us-west-2"

on:
  push:
    branches:
      - master
 
jobs: 
  my_ci_part :
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clon our repo
      uses: actions/checkout@v1
      
    - name: Create ZIP delpoiment package
      run  : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *git.* 
      
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@1
      with:
        aws-acsess-key-id.   : ${{secrets.My_AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.MY_SECRET_KEY}}
        aws-region          : ${{env.AWS-REGION_NAME}}
        
        
    - name : Copy Deployment package to S3 bucket
      run  : aws s3 cp ${{env.DEPLOY_NAME}} s3://${{env.EB_PACKAGE_S3_BUCKET_NAME}}/
      
    - name : prit inchvor ban
      run  : echo "CI PIpline part finished soccessfully!"
      
      
      
        
        
        
        
        
      
