name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET: "lut-it-flask-application-packges"
  EB_APPLICATION_NAME : "MyFlask"
  EB_ENVIRMENT_NAME.  : "MyFlack-env"
  DEPLOY_PACKAGE_NAME : "Flask-app-${{github.sha}}.zip"
  AWS_REGION_NAME.    : "us-west-2"

on:
  push:
    branches:
      - master
 
jobs: 
  my_ci_part:
    ruun-on: ubuntu-latest
    
    steps:
    - name: Git clon our repo
      uses: actions/checkout@v1
      
    - name: Create ZIP delpoiment package
      run : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *git.* 
      
      
