name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET: "lut-it-flask-application-packges"
  EB_APPLICATION_NAME : "MyFlask"
  EB_ENVIRMENT_NAME.  : "MyFlack-env"
  DEPLOY_PACKAGE_NAME : "Flask-app-${{github.sha}}.zip"
  AWS_REGION_NAME.    : "us-east-1"

on:
  push:
    branches:
      - master
 
jobs: 
  my_ci_part :
    runs-on  : ubuntu-latest
    
    steps:
    - name: Git clon our repo
      uses: actions/checkout@v1
      
    - name: Create ZIP delpoiment package
      run  : zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *git.* 
      
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@1
      with:
        aws-acsess-key-id.   : ${{secrets.My_AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.MY_SECRET_KEY}}
        aws-region          : ${{env.AWS-REGION_NAME}}
        
        
    - name : Copy Deployment package to S3 bucket
      run  : aws s3 cp ${{env.DEPLOY_NAME}} s3://${{env.EB_PACKAGE_S3_BUCKET_NAME}}/
      
    - name : prit inchvor ban
      run  : echo "CI PIpline part finished soccessfully!"
      
      
      
  my_cd_part :
   
   runs-on: ubuntu-latest
   needs: [my_ci_part]
    
   steps:
   - name: Configure my AWS credentials
     uses: aws-actions/configure-aws-credentials@1
     with:
        aws-acsess-key-id.   : ${{secrets.MY_AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.MY_SECRET_KEY}}
        aws-region           : ${{env.AWS-REGION_NAME}}
        
   - name: create my new AWS aplikation
     run :
        aws elasticbeanstalk create-application-version \
        --application-name ${{env.EB_APPLICATION_NAME}} \
        --source-bundle S3Bucket="${{env.EB_PACKAGE_S3_BUCKET}}",S3key="${{env.DEPLOY_PACKAGE_NAME}}" \
        --version-label "Ver-${{github.sha}}" \
        --description "CoimmitSHA-${{github.sha}}"
        
   - name: Deploy new ElasticBeanstalk Aplikation version
   
     run: aws elasticbeanstalk update-environment -- enviroment-name ${{env.EB_ENVIRMENT_NAME}} \
          --version-label "Ver-${{github.sha}}"
          
          
   - name:  prit inchvor ban CD
     run : echo "CI PIpline part finished soccessfully!" 
   
      
      
      
        
        
        
        
        
      
